# Base configs
baseurl: "https://maheshnikumbh.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Mahesh Nikumbh"
subtitle: "See the world through my eyes!"
author: "Mahesh Nikumbh"
header:
 title: "Photography"
 subtitle: "by Mahesh Nikumbh"
footer:
 name: "Hey there, my name is Mahesh Nikumbh"
 bio: "Freelance Photographer specialized in : Candid Wedding Photography, Pre-Wedding Photoshoot, Commercial Photography, Events, Portfolios.

For Any Photography Assignments can contact on : Mahesh Nikumbh - 9028107808 , 9890177484 Or maheshnikumbh19@gmail.com"

web_design: "VivekN"
social_urls:
  facebook: "https://www.facebook.com/maheshnikumbh"
  twitter: "https://www.twitter.com/maheshnikumbh"
  instagram: "https://www.instagram.com/maheshnikumbh"
  dribbble: "https://wa.me/919890177484?text=Hi%20There!"
  linkedin: "https://in.linkedin.com/in/maheshnikumbh"
  github: "https://www.github.com/maheshnikumbh"
